grails-app/domain/br/com/reservas/Recurso.groovy
package br.com.reservas

class Recurso {
	
	String nome
	Boolean exigeConfirmacao
	Integer numeroMaxReservas
	String descricao
	Boolean ativo
	BigDecimal valor
	Integer capacidade
	Integer tempoReserva
	UnidadeTempoReserva unidadeTempoReserva
	Cor cor
		
	static hasMany = [reserva:Reserva, indisponibilidades:Indisponibilidade, tipoReserva:TipoReserva, imagens:Imagem]
	
	static belongsTo = [condominio:Condominio]

    static constraints = {
		nome nullable:false
		exigeConfirmacao nullable:false 
		numeroMaxReservas nullable:false
		ativo nullable:false   
		tempoReserva nullable: false
		unidadeTempoReserva nullable: false
		valor nullable:true, scale: 2
		capacidade nullable:true
    }
	
	static mapping = {
		exigeConfirmacao defaultValue: true
		numeroMaxReservas defaultValue: 1
		ativo defaultValue: true
		tempoReserva defaultValue: 24
		descricao defaltValue: "", type: 'text'
	}
	
	String toString(){
		nome
	}
	
	String listaIndisponibilidades(){
		RecursoController recursoController = new RecursoController()
		recursoController.listaIndisponibilidades(this.id)
	}
	
	String listaReservas(){
		RecursoController recursoController = new RecursoController()
		recursoController.listaReservas(this.id)
	}	
}

grails-app/domain/br/com/reservas/TipoPlano.groovy
package br.com.reservas


class TipoPlano {
	Date dataCriacao
	Date dataEncerramento
	BigDecimal valor
	Boolean ativo
	Integer nuMaxRecursos
	Integer nuMaxApartamentos
	String descricao
	
	static constraints = {
		dataCriacao nullable:false
		dataEncerramento nullable:true
		valor nullable:false
		ativo nullable:false
		nuMaxRecursos nullable:false
		nuMaxApartamentos nullable:false
		descricao nullable:false
	}
	
	static mapping = {
		ativo defaultValue:false
		descricao defaltValue: "", type: 'text'
	}
	
	String toString(){
		"R\$ " + String.format("%.2f", (double)valor) + " ( " + nuMaxApartamentos + " apartamentos e " + nuMaxRecursos + " recursos)"
	}
	
	String encodeAsHTML(){
		StringBuilder sb = new StringBuilder()
		
		if(valor){
			sb.append("Valor: R\$ ")
			sb.append(String.format("%.2f", (double)valor))
		}
		
		sb.append("<ul>")		

		sb.append("<li>")			 
		sb.append("N&ordm; m&aacute;ximo de condom&iacute;nios:")
		sb.append("01")
		sb.append("</li>")
		
		if(nuMaxApartamentos){
			sb.append("<li>")
			sb.append("N&ordm; m&aacute;ximo de apartamentos:")
			sb.append(nuMaxApartamentos)
			sb.append("</li>")
		}
		
		if(nuMaxRecursos){
			sb.append("<li>")
			sb.append("N&ordm; m&aacute;ximo de recursos:")
			sb.append(nuMaxRecursos)
			sb.append("</li>")
		}		
		
		sb.append("</ul>")
		sb.toString()
			
//		sb.append('<div class="tipoPlano-box">')
//		sb.append('<div class="tipoPlano-box-valor">Valor: R\$ ')
//		sb.append(String.format("%.2f", (double)valor))
//		sb.append('</div>')
//		sb.append('<div class="tipoPlano-box-valor-mes">por m&ecirc;s</div>')
//		sb.append('<div class="tipoPlano-box-descricao"><span class="marker">►</span>N&ordm; m&aacute;ximo de condom&iacute;nios: <span>')
//		sb.append('01')
//		sb.append('</span></div>')
//		sb.append('<div class="tipoPlano-box-descricao"><span class="marker">►</span>N&ordm; m&aacute;ximo de apartamentos: <span>')
//		sb.append(nuMaxApartamentos)
//		sb.append('</span></div>')
//		sb.append('<div class="tipoPlano-box-descricao"><span class="marker">►</span>N&ordm; m&aacute;ximo de recursos: <span>')
//		sb.append(nuMaxRecursos)
//		sb.append('</span></div>')
//		sb.append('</div>')
//		
//		sb.toString()
	}
}

grails-app/controllers/br/com/reservas/TipoPlanoController.groovy
package br.com.reservas

import org.springframework.dao.DataIntegrityViolationException
import org.springframework.security.access.annotation.Secured

@Secured(['ROLE_ADMIN'])
class TipoPlanoController {

    static allowedMethods = [save: "POST", update: "POST", delete: "POST"]

	@Secured(['IS_AUTHENTICATED_ANONYMOUSLY'])
	def index() {
        redirect(action: "list", params: params)
    }

	@Secured(['IS_AUTHENTICATED_ANONYMOUSLY'])
	def list(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        [tipoPlanoInstanceList: TipoPlano.list(params), tipoPlanoInstanceTotal: TipoPlano.count()]
    }

    def create() {
        [tipoPlanoInstance: new TipoPlano(params)]
    }

    def save() {
        def tipoPlanoInstance = new TipoPlano(params)
        if (!tipoPlanoInstance.save(flush: true)) {
            render(view: "create", model: [tipoPlanoInstance: tipoPlanoInstance])
            return
        }

        flash.message = message(code: 'default.created.message', args: [message(code: 'tipoPlano.label', default: 'TipoPlano'), tipoPlanoInstance.id])
        redirect(action: "show", id: tipoPlanoInstance.id)
    }

    def show(Long id) {
        def tipoPlanoInstance = TipoPlano.get(id)
        if (!tipoPlanoInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'tipoPlano.label', default: 'TipoPlano'), id])
            redirect(action: "list")
            return
        }

        [tipoPlanoInstance: tipoPlanoInstance]
    }

    def edit(Long id) {
        def tipoPlanoInstance = TipoPlano.get(id)
        if (!tipoPlanoInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'tipoPlano.label', default: 'TipoPlano'), id])
            redirect(action: "list")
            return
        }

        [tipoPlanoInstance: tipoPlanoInstance]
    }

    def update(Long id, Long version) {
        def tipoPlanoInstance = TipoPlano.get(id)
        if (!tipoPlanoInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'tipoPlano.label', default: 'TipoPlano'), id])
            redirect(action: "list")
            return
        }

        if (version != null) {
            if (tipoPlanoInstance.version > version) {
                tipoPlanoInstance.errors.rejectValue("version", "default.optimistic.locking.failure",
                          [message(code: 'tipoPlano.label', default: 'TipoPlano')] as Object[],
                          "Another user has updated this TipoPlano while you were editing")
                render(view: "edit", model: [tipoPlanoInstance: tipoPlanoInstance])
                return
            }
        }

        tipoPlanoInstance.properties = params

        if (!tipoPlanoInstance.save(flush: true)) {
            render(view: "edit", model: [tipoPlanoInstance: tipoPlanoInstance])
            return
        }

        flash.message = message(code: 'default.updated.message', args: [message(code: 'tipoPlano.label', default: 'TipoPlano'), tipoPlanoInstance.id])
        redirect(action: "show", id: tipoPlanoInstance.id)
    }

    def delete(Long id) {
        def tipoPlanoInstance = TipoPlano.get(id)
        if (!tipoPlanoInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'tipoPlano.label', default: 'TipoPlano'), id])
            redirect(action: "list")
            return
        }

        try {
            tipoPlanoInstance.delete(flush: true)
            flash.message = message(code: 'default.deleted.message', args: [message(code: 'tipoPlano.label', default: 'TipoPlano'), id])
            redirect(action: "list")
        }
        catch (DataIntegrityViolationException e) {
            flash.message = message(code: 'default.not.deleted.message', args: [message(code: 'tipoPlano.label', default: 'TipoPlano'), id])
            redirect(action: "show", id: id)
        }
    }
}

grails-app/views/tipoPlano/_form.gsp
<%@ page import="br.com.reservas.TipoPlano" %>


<div class="row">
	<div class="col-sm-6">
		<div class="form-group ${hasErrors(bean: tipoPlanoInstance, field: 'dataCriacao', 'error')} required">
			<label for="dataCriacao">
				<i class="glyphicon glyphicon-calendar"></i> 
				<g:message code="tipoPlano.dataCriacao.label" default="Data Criacao" />
				<span class="required-indicator">*</span>
			</label>
			<div class="datepicker-day">
				<g:datePicker name="dataCriacao" precision="day"  value="${tipoPlanoInstance?.dataCriacao}"  />
			</div>	
		</div>
	</div>
	
	<div class="col-sm-6">	
		<div class="form-group ${hasErrors(bean: tipoPlanoInstance, field: 'dataEncerramento', 'error')} ">
			<label for="dataEncerramento">
				<i class="glyphicon glyphicon-calendar"></i> 
				<g:message code="tipoPlano.dataEncerramento.label" default="Data Encerramento" />
				
			</label>
			<div class="datepicker-day">
				<g:datePicker name="dataEncerramento" precision="day"  value="${tipoPlanoInstance?.dataEncerramento}" default="none" noSelection="['': '']" />
			</div>	
		</div>
	</div>
</div>

<hr>

<div class="row">
	<div class="col-sm-3">		
		<div class="form-group ${hasErrors(bean: tipoPlanoInstance, field: 'valor', 'error')} required">
			<label for="valor">
				<i class="glyphicon glyphicon-usd"></i> 
				<g:message code="tipoPlano.valor.label" default="Valor" />
				<span class="required-indicator">*</span>
			</label>
			<g:field type="currency"  class="form-control" name="valor" value="${fieldValue(bean: tipoPlanoInstance, field: 'valor')}" required=""/>
		</div>
	</div>
	
	<div class="col-sm-3">	
		<div class="form-group ${hasErrors(bean: tipoPlanoInstance, field: 'ativo', 'error')} ">
			<label for="ativo">
				<i class="glyphicon glyphicon-ok-sign"></i> 
				<g:message code="tipoPlano.ativo.label" default="Ativo" />
				
			</label>
			<div>
				<g:checkBox name="ativo" value="${tipoPlanoInstance?.ativo}" />
			</div>	
		</div>
	</div>
	
	<div class="col-sm-3">	
		<div class="form-group ${hasErrors(bean: tipoPlanoInstance, field: 'nuMaxRecursos', 'error')} required">
			<label for="nuMaxRecursos">
				<i class="glyphicon glyphicon-info-sign"></i> 
				<g:message code="tipoPlano.nuMaxRecursos.label" default="Nu Max Recursos" />
				<span class="required-indicator">*</span>
			</label>
			<g:field class="form-control" name="nuMaxRecursos" type="number" value="${tipoPlanoInstance.nuMaxRecursos}" required=""/>
		</div>
	</div>
	
	<div class="col-sm-3">	
		<div class="form-group ${hasErrors(bean: tipoPlanoInstance, field: 'nuMaxApartamentos', 'error')} required">
			<label for="nuMaxApartamentos">
				<i class="glyphicon glyphicon-info-sign"></i> 
				<g:message code="tipoPlano.nuMaxApartamentos.label" default="Nu Max Apartamentos" />
				<span class="required-indicator">*</span>
			</label>
			<g:field class="form-control" name="nuMaxApartamentos" type="number" value="${tipoPlanoInstance.nuMaxApartamentos}" required=""/>
		</div>
	</div>
</div>

<hr>		

<div class="row">
	<div class="col-sm-12">
		<div class="form-group ${hasErrors(bean: recursoInstance, field: 'descricao', 'error')} ">
			<label for="descricao">
				<i class="glyphicon glyphicon-info-sign"></i> 
				<g:message code="recurso.descricao.label" default="Descrição" />
				
			</label>
			<g:textArea name="descricao" value="${recursoInstance?.descricao}"/>
		</div>
	</div>
</div>		

grails-app/views/tipoPlano/_list.gsp
	<div class="row">
		<g:each in="${tipoPlanoInstanceList}" status="i" var="tipoPlanoInstance">
			<div class="col-sm-4">
				<g:if test="${tipoPlanoInstance.ativo}">
					<div class="panel panel-default">
						<div class="panel-heading text-center">
							<h4><i class="glyphicon glyphicon-calendar"></i> Opção ${i + 1}</h4>							
						</div>
						<div class="panel-body">
							<h2 class="text-center">
								<g:formatNumber number="${tipoPlanoInstance.valor}" type="currency" currencyCode="BRL" />
							</h2>
								<div class="text-center">	
									${message(code: 'tipoPlano.valor.mes.label', default: 'por mês')}
								</div>
							<h4>
								<i class="glyphicon glyphicon-info-sign"></i> Informações do plano
							</h4>	
							<ul>
								<li>${message(code: 'tipoPlano.nuCondominios.label', default: 'Nº máximo de condomínios: ')}<strong>01</strong></li>
								<li>${message(code: 'tipoPlano.nuMaxApartamentos.label', default: 'Nº máximo de apartamentos: ')}<strong>${fieldValue(bean: tipoPlanoInstance, field: "nuMaxApartamentos")}</strong></li>
								<li>${message(code: 'tipoPlano.nuMaxRecursos.label', default: 'Nº máximo de recursos: ')}<strong>${fieldValue(bean: tipoPlanoInstance, field: "nuMaxRecursos")}</strong></li>
							</ul>
						</div>
						<div class="panel-footer text-center">
							<g:form controller="plano" action="create">
								<g:hiddenField name="tipoPlanoInstanceId" value="${tipoPlanoInstance.id}"/>
								<button type="submit" class="btn btn-primary" id="adicionarPlano">
			                        <i class="glyphicon glyphicon-plus"></i> Adicionar Plano
			                    </button>
							</g:form>
						</div>
					</div>							
				</g:if>
			</div>	
		</g:each>
	</div>				

grails-app/views/tipoPlano/create.gsp
<%@ page import="br.com.reservas.TipoPlano" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'tipoPlano.label', default: 'TipoPlano')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-tipoPlano" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<ol class="breadcrumb">
			<li><a class="home" href="${createLink(uri: '/')}"><i class="glyphicon glyphicon-home"></i> <g:message code="default.home.label"/></a></li>
			<li><g:link class="list" action="list"><i class="glyphicon glyphicon-list"></i> <g:message code="default.list.label" args="[entityName]" /></g:link></li>
		</ol>
		<div id="create-tipoPlano" class="container-fluid" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="alert alert-info"><i class="glyphicon glyphicon-alert"></i> ${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${tipoPlanoInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${tipoPlanoInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form action="save" >
				<div class="panel panel-default">
				    <div class="panel-heading"><g:message code="default.create.label" args="[entityName]" /></div>
				    
				    <div class="panel-body">
				    
						<g:render template="form"/>
						
					</div>	
					<div class="panel-footer">
						<div class="row">
							<div class="col-sm-12">
								<div class="pull-right">
									<button type="submit" class="btn btn-primary" id="create" name="create">
						               	<i class="glyphicon glyphicon-floppy-disk"></i> ${message(code: 'default.button.create.label', default: 'Create')}
						            </button>
								</div>
							</div>
						</div>
					</div>	
				</div>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/tipoPlano/edit.gsp
<%@ page import="br.com.reservas.TipoPlano" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'tipoPlano.label', default: 'TipoPlano')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-tipoPlano" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<ol class="breadcrumb">
			<li><a class="home" href="${createLink(uri: '/')}"><i class="glyphicon glyphicon-home"></i> <g:message code="default.home.label"/></a></li>
			<li><g:link class="list" action="list"><i class="glyphicon glyphicon-list"></i> <g:message code="default.list.label" args="[entityName]" /></g:link></li>
			<li><g:link class="create" action="create"><i class="glyphicon glyphicon-plus"></i> <g:message code="default.new.label" args="[entityName]" /></g:link></li>
		</ol>
		<div id="edit-tipoPlano" class="container-fluid" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="alert alert-info"><i class="glyphicon glyphicon-alert"></i> ${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${tipoPlanoInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${tipoPlanoInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form method="post" >
				<g:hiddenField name="id" value="${tipoPlanoInstance?.id}" />
				<g:hiddenField name="version" value="${tipoPlanoInstance?.version}" />
				
				<div class="panel panel-default">
				    <div class="panel-heading"><g:message code="default.edit.label" args="[entityName]" /></div>
				    
				    <div class="panel-body">
				    	<g:render template="form"/>
				    </div>
				    
				    <div class="panel-footer">
				    	<div class="row">
							<div class="col-sm-12">
								<div class="pull-right">
									<button type="submit" class="btn btn-primary" id="_action_update" name="_action_update">
						            	<i class="glyphicon glyphicon-floppy-disk"></i> ${message(code: 'default.button.update.label', default: 'Update')}
						            </button>
									
									<button type="submit" class="btn btn-primary" id="_action_delete" name="_action_delete" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Tem certeza?')}');">
						            	<i class="glyphicon glyphicon-remove"></i> ${message(code: 'default.button.delete.label', default: 'Delete')}
						            </button>							
								</div>
							</div>
						</div>
				    </div>
				</div>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/tipoPlano/list.gsp
<%@ page import="br.com.reservas.TipoPlano" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'tipoPlano.label', default: 'TipoPlano')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-tipoPlano" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<ol class="breadcrumb">
			<li><a class="home" href="${createLink(uri: '/')}"><i class="glyphicon glyphicon-home"></i> <g:message code="default.home.label"/></a></li>
			<sec:ifAnyGranted roles="ROLE_ADMIN">
				<li><g:link class="create" action="create"><i class="glyphicon glyphicon-plus"></i> <g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</sec:ifAnyGranted>
		</ol>

		<div id="list-tipoPlano" class="container-fluid" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="alert alert-info"><i class="glyphicon glyphicon-alert"></i> ${flash.message}</div>
			</g:if>
		
			<div class="tipoPlano">
				<div class="row">
					<g:each in="${tipoPlanoInstanceList}" status="i" var="tipoPlanoInstance">
						<div class="col-sm-4">
							<g:if test="${tipoPlanoInstance.ativo}">
								<div class="panel panel-default">
									<div class="panel-heading text-center">
										<h4><i class="glyphicon glyphicon-calendar"></i> Opção ${i + 1}</h4>							
									</div>
									<div class="panel-body">
										<h2 class="text-center">
											<g:formatNumber number="${tipoPlanoInstance.valor}" type="currency" currencyCode="BRL" />
										</h2>
											<div class="text-center">	
												${message(code: 'tipoPlano.valor.mes.label', default: 'por mês')}
											</div>
										<h4>
											<i class="glyphicon glyphicon-info-sign"></i> Informações do plano
										</h4>	
										<ul>
											<li>${message(code: 'tipoPlano.nuCondominios.label', default: 'Nº máximo de condomínios: ')}<strong>01</strong></li>
											<li>${message(code: 'tipoPlano.nuMaxApartamentos.label', default: 'Nº máximo de apartamentos: ')}<strong>${fieldValue(bean: tipoPlanoInstance, field: "nuMaxApartamentos")}</strong></li>
											<li>${message(code: 'tipoPlano.nuMaxRecursos.label', default: 'Nº máximo de recursos: ')}<strong>${fieldValue(bean: tipoPlanoInstance, field: "nuMaxRecursos")}</strong></li>
										</ul>
									</div>
									<div class="panel-footer text-center">
										<g:form controller="plano" action="create">
											<g:hiddenField name="tipoPlanoInstanceId" value="${tipoPlanoInstance.id}"/>
											<button type="submit" class="btn btn-primary" id="adicionarPlano">
						                        <i class="glyphicon glyphicon-plus"></i> Adicionar Plano
						                    </button>
										</g:form>
									</div>
								</div>
							</g:if>
						</div>
					</g:each>
				</div>	
			</div>
		</div>			
	</body>
</html>

grails-app/views/tipoPlano/show.gsp
<%@ page import="br.com.reservas.TipoPlano" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'tipoPlano.label', default: 'TipoPlano')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-tipoPlano" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="list"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-tipoPlano" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="alert alert-info"><i class="glyphicon glyphicon-alert"></i> ${flash.message}</div>
			</g:if>
			<ol class="property-list tipoPlano">
			
				<g:if test="${tipoPlanoInstance?.dataCriacao}">
				<li class="fieldcontain">
					<span id="dataCriacao-label" class="property-label"><g:message code="tipoPlano.dataCriacao.label" default="Data Criacao" /></span>
					
						<span class="property-value" aria-labelledby="dataCriacao-label"><g:formatDate date="${tipoPlanoInstance?.dataCriacao}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${tipoPlanoInstance?.dataEncerramento}">
				<li class="fieldcontain">
					<span id="dataEncerramento-label" class="property-label"><g:message code="tipoPlano.dataEncerramento.label" default="Data Encerramento" /></span>
					
						<span class="property-value" aria-labelledby="dataEncerramento-label"><g:formatDate date="${tipoPlanoInstance?.dataEncerramento}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${tipoPlanoInstance?.valor}">
				<li class="fieldcontain">
					<span id="valor-label" class="property-label"><g:message code="tipoPlano.valor.label" default="Valor" /></span>
					
						<span class="property-value" aria-labelledby="valor-label"><g:fieldValue bean="${tipoPlanoInstance}" field="valor"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${tipoPlanoInstance?.ativo}">
				<li class="fieldcontain">
					<span id="ativo-label" class="property-label"><g:message code="tipoPlano.ativo.label" default="Ativo" /></span>
					
						<span class="property-value" aria-labelledby="ativo-label"><g:formatBoolean boolean="${tipoPlanoInstance?.ativo}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${tipoPlanoInstance?.nuMaxRecursos}">
				<li class="fieldcontain">
					<span id="nuMaxRecursos-label" class="property-label"><g:message code="tipoPlano.nuMaxRecursos.label" default="Nu Max Recursos" /></span>
					
						<span class="property-value" aria-labelledby="nuMaxRecursos-label"><g:fieldValue bean="${tipoPlanoInstance}" field="nuMaxRecursos"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${tipoPlanoInstance?.nuMaxApartamentos}">
				<li class="fieldcontain">
					<span id="nuMaxApartamentos-label" class="property-label"><g:message code="tipoPlano.nuMaxApartamentos.label" default="Nu Max Apartamentos" /></span>
					
						<span class="property-value" aria-labelledby="nuMaxApartamentos-label"><g:fieldValue bean="${tipoPlanoInstance}" field="nuMaxApartamentos"/></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form>
				<fieldset class="buttons">
					<g:hiddenField name="id" value="${tipoPlanoInstance?.id}" />
					<g:link class="edit" action="edit" id="${tipoPlanoInstance?.id}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>